version: '3.8'

services:
  postgresql:
    container_name: postgres
    image: postgres:15.3
    restart: always
    volumes:
      - transtour-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=transtour-user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=transtour-db
      - PGDATA=/data/postgres
    ports:
      - 5432:5432

volumes:
  transtour-data:
    external: true